export enum EventType {
  ACCIDENT = 'ACCIDENT',
  CONSTRUCTION = 'CONSTRUCTION',
  METRO_WORK = 'METRO_WORK',
  WATER_LOGGING = 'WATER_LOGGING',
  PROTEST = 'PROTEST',
  HEAVY_TRAFFIC = 'HEAVY_TRAFFIC',
  ROAD_BLOCK = 'ROAD_BLOCK',
}
